config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    get 'search', to: 'searches#index', as: 'search'
    resources :users, only: [:index, :show, :edit, :update]
    resources :artists, only: [:index, :new, :show, :edit, :create, :update] do
      resources :topics, only: [:index, :new, :show, :edit, :create, :update] do
        resources :comments, only: [:index, :destroy]
      end
    end
    resources :reports, only: [:index, :show, :edit, :update] do
      patch :update_status, on: :member
    end
    resources :genres, only: [:index, :edit, :create, :update]
    resources :groups, only: [:index, :new, :show, :edit, :create, :update]
  end

  # ユーザー用
  # URL /users/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root 'homes#top'
    get 'homes/about', to: "homes#about"
    get 'search', to: 'searches#index', as: 'search'
    get 'users/mypage', to: "users#mypage"
    get 'users/unsubscribe', to: "users#unsubscribe"
    patch 'users/withdraw', to: "users#withdraw" #退会処理
    get 'artist_tags/:name', to: 'artist_tags#show', as: 'artist_tag'
    get 'group_tags/:name', to: 'group_tags#show', as: 'group_tag'

    resources :users, only: [:show, :edit, :create, :update] do
      resources :relationships, only: [:create, :destroy]
    end

    resources :artists, only: [:index, :new, :show, :edit, :create, :update] do
      member do
        get :favorited_users #いいねをつけたユーザーの一覧表示
      end
      resource :favorites, only: [:create, :destroy]# アーティストごとの「いいね」
      resources :artist_tags, only: [:create, :destroy]
      resources :topics, only: [:new, :show, :edit, :create, :update] do
        resources :topic_tags, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy]
      end
    end
  
    resources :favorites, only: [:create, :destroy]  # ユーザーによるアーティスト「いいね」
    resources :reports, only: [:new, :create]
    resources :groups, only: [:index, :new, :show, :edit, :create, :update] do
      resource :group_membership, only: [:create, :destroy]
      resources :group_comments, only: [:create, :destroy]
      resources :chat_messages, only: [:index, :create]
    end
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin! 
  
  def top
    @unchecked_report_count = Report.where(status: "unchecked").count
    @guest_user_count = User.where(guest: true).count
    @artist_count = Artist.count
    @group_count = Group.count
    @users = User.without_guests.includes(:artists, :topics, :owned_groups, :comments).order(created_at: :desc).limit(5)
    @user_count = User.where(guest: [false, nil]).count
    @groups = Group.order(created_at: :desc).limit(5)
    @artists = Artist.order(created_at: :desc).limit(5)
    @reports = Report.order(created_at: :desc).limit(5)
  end
end

app/views/admin/homes/top.html.erb
<div class="container admin-white-bg p-5">
  <h1 class="display-5 mb-5">STAN COLONY管理者画面</h1>
  <h4 class="mb-3 ">
    <%= link_to admin_reports_path, class: "admin-top-link-color" do %>
      未対応の通報: <span class="text-danger h4"><%= @unchecked_report_count %></span>件
    <% end %>
  </h4>

  <h4 class="admin-title">統計情報</h4>
  <table class="table table-borderless">
    <tbody>
      <tr>
        <th>ユーザー数</th>
        <td><%= @user_count %></td>
      </tr>
      <tr>
        <th>ゲストユーザー数</th>
        <td><%= @guest_user_count %></td>
      </tr>
      <tr>
        <th>アーティスト数</th>
        <td><%= @artist_count %></td>
      </tr>
      <tr>
        <th>コミュニティ数</th>
        <td><%= @group_count %></td>
      </tr>
    </tbody>
  </table>

  <h4 class="admin-title mb-4">最近の更新情報</h4>

  <div class="mb-3">
    <h5><%= link_to "最近の通報（最新5件）", admin_reports_path, class: "admin-top-link-color" %></h5>
    <ul>
      <% @reports.each do |report| %>
        <li>
          <% if report.reportable.present? %>
            <%= reportable_link(report) %>
          <% else %>
            通報対象が存在しません
          <% end %>
          （<%= l(report.created_at, format: :short) %>）
          （<%= link_to "詳細", admin_report_path(report) %>）
        </li>
      <% end %>
    </ul>
  </div>

  <div class="mb-3">
    <h5><%= link_to "最近作成されたアーティスト（最新5件）", admin_artists_path, class: "admin-top-link-color" %></h5>
    <ul>
      <% @artists.each do |artist| %>
        <li><%= link_to truncate(artist.name, length: 50), admin_artist_path(artist) %>（<%= l(artist.created_at, format: :short) %>）</li>
      <% end %>
    </ul>
  </div>

  <div class="mb-3">
    <h5><%= link_to "最近作成されたコミュニティ（最新5件）", admin_groups_path, class: "admin-top-link-color" %></h5>
    <ul>
      <% @groups.each do |group| %>
        <li><%= link_to truncate(group.name, length: 50), admin_group_path(group) %>（<%= l(group.created_at, format: :short) %>）</li>
      <% end %>
    </ul>
  </div>

  <div class="mb-3">
    <h5><%= link_to "最近登録されたユーザー（最新5件）", admin_users_path, class: "admin-top-link-color" %></h5>
    <ul>
      <% @users.each do |user| %>
        <li><%= link_to truncate(user.name, length: 30), admin_user_path(user) %>（<%= l(user.created_at, format: :short) %>）</li>
      <% end %>
    </ul>
  </div>
</div>